# Generated by Django 3.1.7 on 2021-10-02 11:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockBrokerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Stock Broker Details',
            },
        ),
        migrations.CreateModel(
            name='lookingToInvestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorLTID', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment In Details',
            },
        ),
        migrations.CreateModel(
            name='linkedInModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerIIM', to=settings.AUTH_USER_MODEL)),
                ('profileOwnerMM', models.ManyToManyField(blank=True, null=True, related_name='profileOwnerMMIIM', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Iinked In Model',
            },
        ),
        migrations.CreateModel(
            name='investorPersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobileNumber', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True)),
                ('panNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('uploadPan', models.FileField(blank=True, null=True, upload_to='investor/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('aadharNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('uploadAadhar', models.FileField(blank=True, null=True, upload_to='investor/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('address', models.TextField(blank=True, null=True)),
                ('pinCode', models.BigIntegerField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorIPD', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cityIPD', to='employeeApp.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countryIPD', to='employeeApp.country')),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerIPD', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stateIPD', to='employeeApp.state')),
            ],
            options={
                'verbose_name_plural': 'Investor Personal Details',
            },
        ),
        migrations.CreateModel(
            name='investorDMATDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depository', models.CharField(blank=True, choices=[('NSDL', 'NSDL'), ('CDSL', 'CDSL')], max_length=10, null=True)),
                ('dmatClientMasterReport', models.FileField(blank=True, null=True, upload_to='investor/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('dpID', models.CharField(blank=True, max_length=1000, null=True)),
                ('clientID', models.BigIntegerField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('profileOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerIDD', to=settings.AUTH_USER_MODEL)),
                ('stockBroker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockBrokerIDD', to='investorApp.stockbrokerdetails')),
            ],
            options={
                'verbose_name_plural': 'Investor DMAT Details',
            },
        ),
        migrations.CreateModel(
            name='investorBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=1000)),
                ('accountHolder', models.CharField(blank=True, max_length=1000, null=True)),
                ('accountNumber', models.BigIntegerField(blank=True, null=True)),
                ('accountType', models.CharField(blank=True, choices=[('Current', 'Current'), ('Saving', 'Saving')], max_length=10, null=True)),
                ('ifsc_Code', models.CharField(blank=True, max_length=1000, null=True)),
                ('cancelledCheque', models.FileField(blank=True, null=True, upload_to='investor/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorIBD', to=settings.AUTH_USER_MODEL)),
                ('profileOwner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerIBD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Investor Bank Details',
            },
        ),
        migrations.CreateModel(
            name='investmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentPortfolio', models.CharField(blank=True, choices=[('< 1 Lac', '< 1 Lac'), ('1 - 5 Lac', '1 - 5 Lac'), ('5 - 10 Lac', '5 - 10 Lac'), ('10 - 25 Lac', '10 - 25 Lac'), ('25 - 50 Lac', '25 - 50 La'), ('50 - 100 Lac', '50 - 100 Lac'), ('1 - 5 Crores', '1 - 5 Crores'), ('5 - 10 Crores', '5 - 10 Crores'), ('10 - 25 Crores', '10 - 25 Crores'), ('25 - 50 Crores', '25 - 50 Crores'), ('50 - 100 Crores', '50 - 100 Crores'), ('100 + Crores', '100 + Crores')], max_length=50, null=True)),
                ('secondaryMarket', models.BooleanField(blank=True, null=True)),
                ('primaryMarket', models.BooleanField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorID', to=settings.AUTH_USER_MODEL)),
                ('lookingToInvest', models.ManyToManyField(blank=True, null=True, to='investorApp.lookingToInvestDetails')),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerID', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Investment Details',
            },
        ),
    ]
