# Generated by Django 3.1.7 on 2021-10-02 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinmodel',
            name='profileOwnerMM',
            field=models.ManyToManyField(blank=True, related_name='profileOwnerMMIIM', to=settings.AUTH_USER_MODEL),
        ),
    ]
