# Generated by Django 3.1.7 on 2021-10-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investorApp', '0002_auto_20211002_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdetails',
            name='lookingToInvest',
            field=models.ManyToManyField(blank=True, to='investorApp.lookingToInvestDetails'),
        ),
    ]
