# Generated by Django 3.1.7 on 2021-10-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investorApp', '0003_auto_20211002_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookingtoinvestdetails',
            options={'verbose_name': 'Looking To Invest Details'},
        ),
    ]
