# Generated by Django 3.1.7 on 2021-10-08 12:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockBrokerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Stock Broker Detail',
            },
        ),
        migrations.CreateModel(
            name='registerWithSEBIDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorRWSD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Register With SEBI Detail',
            },
        ),
        migrations.CreateModel(
            name='linkedInModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerIIMS', to=settings.AUTH_USER_MODEL)),
                ('profileOwnerMM', models.ManyToManyField(blank=True, related_name='profileOwnerMMIIMS', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Iinked In Models',
            },
        ),
        migrations.CreateModel(
            name='dealerTransferFacilityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferShares', models.CharField(blank=True, choices=[('Physical DIS', 'PhysicalDIS'), ('Online eDIS', 'Online eDIS'), ('NSDL Speed-e', 'CDSL Easi'), ('CDSL Easi', 'CDSL Easi')], max_length=50, null=True)),
                ('transferFileProof', models.FileField(blank=True, null=True, upload_to='dealer/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerDTFD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dealer Transfer Shares Detail',
            },
        ),
        migrations.CreateModel(
            name='dealersNetworkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkPart', models.CharField(choices=[('Unlisted Share Dealer', 'Unlisted Share Dealer'), ('Unlisted PreIPO Dealer', 'Unlisted PreIPO Dealer'), ('others', 'others')], default='draft', max_length=100)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorDND', to=settings.AUTH_USER_MODEL)),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerDND', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Network Part Of Details',
            },
        ),
        migrations.CreateModel(
            name='dealerPersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobileNumber', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True)),
                ('panNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('uploadPan', models.FileField(blank=True, null=True, upload_to='dealer/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('aadharNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('uploadAadhar', models.FileField(blank=True, null=True, upload_to='dealer/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('address', models.TextField(blank=True, null=True)),
                ('pinCode', models.BigIntegerField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorDPD', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cityDPD', to='employeeApp.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countryDPD', to='employeeApp.country')),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerDPD', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stateDPD', to='employeeApp.state')),
            ],
            options={
                'verbose_name_plural': 'Dealer Personal Detail',
            },
        ),
        migrations.CreateModel(
            name='dealerDematDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depository', models.CharField(blank=True, choices=[('NSDL', 'NSDL'), ('CDSL', 'CDSL')], max_length=10, null=True)),
                ('dmatClientMasterReport', models.FileField(blank=True, null=True, upload_to='dealer/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('dpID', models.CharField(blank=True, max_length=1000, null=True)),
                ('clientID', models.BigIntegerField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('profileOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerDDD', to=settings.AUTH_USER_MODEL)),
                ('stockBroker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockBrokerDDD', to='dealerApp.stockbrokerdetail')),
            ],
            options={
                'verbose_name_plural': 'Dealer Demat Detail',
            },
        ),
        migrations.CreateModel(
            name='dealerCompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfOrganization', models.CharField(blank=True, max_length=1000, null=True)),
                ('companyAddress', models.TextField(blank=True, null=True)),
                ('pinCode', models.BigIntegerField(blank=True, null=True)),
                ('companyWebsiteURL', models.URLField(blank=True, max_length=1000, null=True)),
                ('SEBIRegistration', models.CharField(blank=True, max_length=1000, null=True)),
                ('panCardNumber', models.CharField(blank=True, max_length=1000, null=True)),
                ('panCard', models.FileField(blank=True, null=True, upload_to='dealer/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorDCD', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cityDCD', to='employeeApp.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countryDCD', to='employeeApp.country')),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerDCD', to=settings.AUTH_USER_MODEL)),
                ('registerWithSEBI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registerWithSEBIDCD', to='dealerApp.registerwithsebidetail')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stateDCD', to='employeeApp.state')),
            ],
            options={
                'verbose_name_plural': 'Dealer Company Detail',
            },
        ),
        migrations.CreateModel(
            name='dealerBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=1000)),
                ('accountHolder', models.CharField(blank=True, max_length=1000, null=True)),
                ('accountNumber', models.BigIntegerField(blank=True, null=True)),
                ('accountType', models.CharField(blank=True, choices=[('Current', 'Current'), ('Saving', 'Saving')], max_length=10, null=True)),
                ('ifsc_Code', models.CharField(blank=True, max_length=1000, null=True)),
                ('cancelledCheque', models.FileField(blank=True, null=True, upload_to='dealer/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorDBD', to=settings.AUTH_USER_MODEL)),
                ('profileOwner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerDBD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dealer Bank Detail',
            },
        ),
    ]
