# Generated by Django 3.1.7 on 2021-10-12 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerdematdetail',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorDDD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealertransferfacilitydetail',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorDTFD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linkedinmodels',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorIIMS', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockbrokerdetail',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorSBD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registerwithsebidetail',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorRWSDD', to=settings.AUTH_USER_MODEL),
        ),
    ]
