# Generated by Django 3.1.7 on 2021-10-06 09:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockBrokerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Stock Broker Details',
            },
        ),
        migrations.CreateModel(
            name='transferFacilityDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferShares', models.CharField(blank=True, choices=[('Physical DIS', 'PhysicalDIS'), ('Online eDIS', 'Online eDIS'), ('NSDL Speed-e', 'CDSL Easi'), ('CDSL Easi', 'CDSL Easi')], max_length=50, null=True)),
                ('transferFileProof', models.FileField(blank=True, null=True, upload_to='institutional/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerTFD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transfer Shares Details',
            },
        ),
        migrations.CreateModel(
            name='registerWithSEBIDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorRWSD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Register With SEBI Details',
            },
        ),
        migrations.CreateModel(
            name='majorSectorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorMSD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Major Sector Details',
            },
        ),
        migrations.CreateModel(
            name='lookingToInvestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorLTID', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Looking To Invest Details',
            },
        ),
        migrations.CreateModel(
            name='lookingForPrivateCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorLFPC', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Looking For Private Company',
            },
        ),
        migrations.CreateModel(
            name='institutionalPersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactPersonName', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobileNumber', models.BigIntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorIPD', to=settings.AUTH_USER_MODEL)),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerIPD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Institutional Personal Details',
            },
        ),
        migrations.CreateModel(
            name='institutionalInvestmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetsYouAreManaging', models.CharField(blank=True, choices=[('< 1 Lac', '< 1 Lac'), ('1 - 5 Lac', '1 - 5 Lac'), ('5 - 10 Lac', '5 - 10 Lac'), ('10 - 25 Lac', '10 - 25 Lac'), ('25 - 50 Lac', '25 - 50 La'), ('50 - 100 Lac', '50 - 100 Lac'), ('1 - 5 Crores', '1 - 5 Crores'), ('5 - 10 Crores', '5 - 10 Crores'), ('10 - 25 Crores', '10 - 25 Crores'), ('25 - 50 Crores', '25 - 50 Crores'), ('50 - 100 Crores', '50 - 100 Crores'), ('100 + Crores', '100 + Crores')], max_length=50, null=True)),
                ('secondaryMarket', models.BooleanField(blank=True, null=True)),
                ('primaryMarket', models.BooleanField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorIID', to=settings.AUTH_USER_MODEL)),
                ('lookingForPrivateCompany', models.ManyToManyField(blank=True, to='institutionalApp.lookingForPrivateCompany')),
                ('lookingToInvest', models.ManyToManyField(blank=True, to='institutionalApp.lookingToInvestDetails')),
                ('majorSector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majorSectorIID', to='institutionalApp.majorsectordetails')),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerIID', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Institutional Investment Details',
            },
        ),
        migrations.CreateModel(
            name='institutionalDematDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depository', models.CharField(blank=True, choices=[('NSDL', 'NSDL'), ('CDSL', 'CDSL')], max_length=10, null=True)),
                ('dmatClientMasterReport', models.FileField(blank=True, null=True, upload_to='investor/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('dpID', models.CharField(blank=True, max_length=1000, null=True)),
                ('clientID', models.BigIntegerField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('profileOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerIDD', to=settings.AUTH_USER_MODEL)),
                ('stockBroker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockBrokerIDD', to='institutionalApp.stockbrokerdetails')),
            ],
            options={
                'verbose_name_plural': 'Institutional Demat Details',
            },
        ),
        migrations.CreateModel(
            name='institutionalCompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfOrganization', models.CharField(blank=True, max_length=1000, null=True)),
                ('companyAddress', models.TextField(blank=True, null=True)),
                ('pinCode', models.BigIntegerField(blank=True, null=True)),
                ('companyWebsiteURL', models.URLField(blank=True, max_length=1000, null=True)),
                ('SEBIRegistration', models.CharField(blank=True, max_length=1000, null=True)),
                ('panCardNumber', models.CharField(blank=True, max_length=1000, null=True)),
                ('panCard', models.FileField(blank=True, null=True, upload_to='institutional/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorICD', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cityICD', to='employeeApp.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countryICD', to='employeeApp.country')),
                ('profileOwner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerICD', to=settings.AUTH_USER_MODEL)),
                ('registerWithSEBI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registerWithSEBIICD', to='institutionalApp.registerwithsebidetails')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stateICD', to='employeeApp.state')),
            ],
            options={
                'verbose_name_plural': 'Institutional Company Details',
            },
        ),
        migrations.CreateModel(
            name='institutionalBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=1000)),
                ('accountHolder', models.CharField(blank=True, max_length=1000, null=True)),
                ('accountNumber', models.BigIntegerField(blank=True, null=True)),
                ('accountType', models.CharField(blank=True, choices=[('Current', 'Current'), ('Saving', 'Saving')], max_length=10, null=True)),
                ('ifsc_Code', models.CharField(blank=True, max_length=1000, null=True)),
                ('cancelledCheque', models.FileField(blank=True, null=True, upload_to='institutional/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorIBD', to=settings.AUTH_USER_MODEL)),
                ('profileOwner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerIBD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Institutional Bank Details',
            },
        ),
    ]
